-- MySQL Script generated by MySQL Workbench
-- Adaptado para tarea2

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tarea2` ;

CREATE SCHEMA IF NOT EXISTS `tarea2`
DEFAULT CHARACTER SET utf8mb4 ;

USE `tarea2` ;

-- -----------------------------------------------------
-- Table `tarea2`.`miembro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`miembro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL COMMENT 'estudiante | funcionario | academico',
  `nivel` VARCHAR(20) NULL DEFAULT NULL COMMENT 'pregrado | postgrado (solo estudiantes)',
  `detalle` VARCHAR(200) NULL DEFAULT NULL COMMENT 'departamento o unidad segun tipo',
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `rut_UNIQUE` (`rut` ASC)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tarea2`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_miembro` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `dias` VARCHAR(200) NOT NULL COMMENT 'dias separados por coma',
  `horario` VARCHAR(50) NOT NULL COMMENT 'HH:MM - HH:MM',
  `link` VARCHAR(300) NULL DEFAULT NULL,

  PRIMARY KEY (`id`),

  INDEX `fk_act_miembro_idx` (`id_miembro` ASC),

  CONSTRAINT `fk_act_miembro`
    FOREIGN KEY (`id_miembro`)
    REFERENCES `tarea2`.`miembro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tarea2`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_miembro` INT NOT NULL,
  `nombre_orig` VARCHAR(300) NOT NULL COMMENT 'nombre original enviado por cliente',
  `nombre_srv` VARCHAR(300) NOT NULL COMMENT 'nombre generado en servidor (UUID)',

  PRIMARY KEY (`id`),

  INDEX `fk_foto_miembro_idx` (`id_miembro` ASC),

  CONSTRAINT `fk_foto_miembro`
    FOREIGN KEY (`id_miembro`)
    REFERENCES `tarea2`.`miembro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;